# 皮肤：淡然 flypy.cc
[color]
# 中间层 状态栏背景 上部
status_back_color=#ECEFF8,#0C101B
# 顶层 键区背景 中部
keyregion_back_color=#DCE0EB,#1C202B
# 底层背景
board_back_color=status_back_color
# 底层背景图片
board_back_icon=

# 透明色
tm_color=#00FFFFFF,#00FFFFFF
tm_hc_color=#ccD8D8D8,#cc303030
tm_key_color=#ccFFFFFF,#cc6A6A6A
key_light_color=#66FFFFFF,#666A6A6A

# 状态栏
logo_icon=vt_logo.png,vt_logo_ye.png
cnen_icon=vt_cn.png,vt_cn_ye.png,vt_en.png,vt_en_ye.png
emoji_icon=vt_emoji.png,vt_emoji_ye.png
clip_icon=vt_clip.png,vt_clip_ye.png
riye_icon=vt_day.png,vt_day_ye.png
open_icon=vt_open.png,vt_open_ye.png
hide_icon=vt_hide.png,vt_hide_ye.png
urf_icon=vt_urf.png,vt_urf_ye.png
urf_cicon=vt_urf.png,vt_urf_ye.png
yuyb_icon=vt_yuyb.png,vt_yuyb_ye.png
yuyb_cicon=vt_yuyb.png,vt_yuyb_ye.png
back_icon=vt_back.png,vt_back_ye.png

# 候选栏
code_color=#aaaaaa,#888888
hilited_code_color=#aaaaaa,#888888
order_color=#aaaaaa,#888888
hilited_order_color=#aaaaaa,#888888
hilited_text_color=#D75642,#FFB5B0
text_color=#666666,#aaaaaa
text_tp_color=#008080,#0099FF
text_lx_color=#008080,#0099FF
back_color=#A8A7A6,#F2F2F2
border_color=
hilited_candidate_back_color=

# 普通键
key_back_color=bdb.png,bdb_ye.png
hilited_key_back_color=bdb_ax.png,bdb_ye.png
key_text_color=#1B2927,#FAFAFA
hilited_key_text_color=#FFFFFF,#ADB1BB

key_symbol_color=#7B8987,#BDBABE,#008080,#FFB5B0
space_symbol_color=#7B8987,#BDBABE
hilited_key_symbol_color=#DE9F16,#ADB1BB
key_border_color=#DDDDDD,#2c3032
# shift键锁定 border_ye282828 303436
on_key_back_color=gnb.png,gnb_ye.png
on_key_text_color=#D75642,#FFB5B0
hilited_on_key_back_color=gnb_ax.png,gnb_ax_ye.png
hilited_on_key_text_color=hilited_key_text_color
# shift键常态及功能键
off_key_back_color=gnb.png,gnb_ye.png
hilited_off_key_back_color=gnb_ax.png,gnb_ax_ye.png
off_key_text_color=#1B2927,#FCFAFD
hilited_off_key_text_color=hilited_key_text_color

# 大写dx 回删hs 数字sz 空格kg 回车hc 返回fh 删除ui 等于dy ， shift En caps Esc 图片
dx_icon=tb_dx.png,tb_dx_ye.png,tb_en.png,tb_en_ye.png,tb_caps.png,tb_caps_ye.png,tb_esc.png,tb_esc_ye.png
dxen_icon=dx_icon
hs_icon=tb_hs.png,tb_hs_ye.png
sz_icon=tb_sz.png,tb_sz_ye.png
kg_icon=tb_kg.png,tb_kg_ye.png,tb_kgyz.png,tb_kgyz_ye.png
hc_icon=tb_hc.png,tb_hc_ye.png
fh_icon=tb_fh.png,tb_fh_ye.png
ui_icon=tb_ui.png,tb_ui_ye.png
dy_icon=tb_dy.png,tb_dy_ye.png

ks_icon=tb_ks.png,tb_ks_ye.png,tb_ksyz.png,tb_ksyz_ye.png

jhx_icon=tb_jhx.png,tb_jhx_ye.png
dhx_icon=tb_dhx.png,tb_dhx_ye.png

# 大写 回删 数字 空格 回车
dx_text_color=#1B2927,#FCFAFD,#1B2927,#FCFAFD,#D75642,#FFB5B0
hs_text_color=#1B2927,#FCFAFD
sz_text_color=#1B2927,#FCFAFD
kg_text_color=#1B2927,#FCFAFD,#008080,#FFB5B0
hc_text_color=#1B2927,#FCFAFD
dh_text_color=off_key_text_color
jh_text_color=off_key_text_color
dh_symbol_color=key_symbol_color
jh_symbol_color=#1B2927,#BDBABE,#D75642,#0099FF
hx_text_color=off_key_text_color

# 主键盘背景 ABC 
abc_back_color=key.png,key_ye.png
# 大写4组背景 shift En caps Esc
dx_back_color=gnb.png,gnb_ye.png
hs_back_color=gnb.png,gnb_ye.png
sz_back_color=gnb.png,gnb_ye.png
kg_back_color=kgb.png,kgb_ye.png
hc_back_color=hcb.png,hcb_ye.png
dh_back_color=gnb.png,gnb_ye.png
jh_back_color=gnb.png,gnb_ye.png

dx_border_color=key_border_color
hs_border_color=dx_border_color
sz_border_color=dx_border_color
hc_border_color=dx_border_color
kg_border_color=key_border_color
dh_border_color=key_border_color
jh_border_color=key_border_color
off_key_border_color=dx_border_color

dx_click_text_color=hilited_off_key_text_color
hs_click_text_color=hilited_off_key_text_color
sz_click_text_color=hilited_off_key_text_color
kg_click_text_color=hilited_off_key_text_color
hc_click_text_color=hilited_off_key_text_color
dh_click_text_color=hilited_off_key_text_color
jh_click_text_color=hilited_off_key_text_color

abc_click_back_color=key_ax.png,key_ax_ye.png
dx_click_back_color=gnb_ax.png,gnb_ax_ye.png
hs_click_back_color=gnb_ax.png,gnb_ax_ye.png
sz_click_back_color=gnb_ax.png,gnb_ax_ye.png
kg_click_back_color=kgb_ax.png,kgb_ax_ye.png
hc_click_back_color=gnb_ax.png,gnb_ax_ye.png
dh_click_back_color=bdb_ax.png,bdb_ax_ye.png
jh_click_back_color=bdb_ax.png,bdb_ax_ye.png

# 气泡预览
preview_back_color=key_back_color
preview_text_color=key_text_color
shadow_color=

#助记  笔画键 上下标 #DB6A66
bh_text_color=#DF9590,#60E0E0
bh_small_color=#7B8987,#ADAAAE,#7B8987,#ADAAAE,#7B8987,#ADAAAE,#DF9590,#60E0E0
vj_symbol_color=#7B8987,#ADAAAE,#008080,#FFB5B0
viu_symbol_color=#7B8987,#ADAAAE,#7B8987,#ADAAAE,#7B8987,#ADAAAE,#1B2927,#FAFAFA

#状态栏文字色、高亮背景
vt_text_color=#505657,#FFFDFF,#D75642,#0099FF
hilited_vt_back_color=hilited_key_back_color
#架空行输入法、隐藏键
gn_text_color=vt_text_color
hilited_gn_back_color=hilited_vt_back_color
#辅键盘 菜单文字 高亮背景
cd_text_color=#888888,#888888
hilited_cd_text_color=hilited_text_color
hilited_cd_back_color=hilited_key_back_color

#功能键盘 fun
fun_text_color=#1B2927,#FCFAFD,#008080,#60E0E0
fun_symbol_color=#888888,#888888
hilited_fun_back_color=hilited_key_back_color

#滑动区域
#背景色
sub_back_color=#FFFFFE,#393D40
#文字色
sub_text_color=off_key_text_color
#编码提示色
sub_code_color=space_symbol_color
#划线颜色
sub_line_color=#33999999,#339E9E9E

# 按钮
#背景色
subbtn_back_color=off_key_back_color
#按下色
subbtn_click_color=hilited_off_key_back_color
#文字色
subbtn_text_color=off_key_text_color
#边框色
subbtn_border_color=off_key_border_color

# 浮动候选
# 编码
fd_bm_color=hc_text_color
# 编码窗背景
fd_bmback_color=tm_hc_color
# 编码窗边框
fd_bmborder_color=hc_border_color

# 候选背景
fd_back_color=tm_key_color
# 边框
fd_border_color=key_border_color
# 首选序号
fd_hiorder_color=key_symbol_color
# 次选序号
fd_order_color=key_symbol_color
# 首选
fd_hitext_color=#D75642,#60E0E0
# 次选选
fd_text_color=key_text_color
# 双检
fd_tptext_color=bh_text_color
# 联想
fd_lxtext_color=bh_text_color
# 首选提示码
fd_hicode_color=key_symbol_color
# 次选提示码
fd_code_color=key_symbol_color

#sicon
wf_sicon=A0wf.png,A0wf_ye.png
dg_sicon=A0dg.png,A0dg_ye.png
ju_sicon=A0ju.png,A0ju_ye.png
jh_sicon=A0jh.png,A0jh_ye.png
#icon
dh_icon=A0dh.png,A0dh_ye.png
jh_icon=A0jh.png,A0jh_ye.png
dz_icon=A0dz.png,A0dz_ye.png
ju_icon=A0ju.png,A0ju_ye.png
szdz_icon=dz_icon
szju_icon=ju_icon

q_icon=A1q.png,A1q_ye.png
w_icon=A1w.png,A1w_ye.png
e_icon=A1e.png,A1e_ye.png
ee_icon=A1ee.png,A1ee_ye.png
r_icon=A1r.png,A1r_ye.png
t_icon=A1t.png,A1t_ye.png
y_icon=A1y.png,A1y_ye.png
u_icon=A1u.png,A1u_ye.png
i_icon=A1i.png,A1i_ye.png
ch_icon=A1ch.png,A1ch_ye.png
o_icon=A1o.png,A1o_ye.png
p_icon=A1p.png,A1p_ye.png

a_icon=A1a.png,A1a_ye.png
s_icon=A1s.png,A1s_ye.png
d_icon=A1d.png,A1d_ye.png
f_icon=A1f.png,A1f_ye.png
g_icon=A1g.png,A1g_ye.png
h_icon=A1h.png,A1h_ye.png
hh_icon=A1hh.png,A1hh_ye.png
j_icon=A1j.png,A1j_ye.png
k_icon=A1k.png,A1k_ye.png
l_icon=A1l.png,A1l_ye.png

z_icon=A1z.png,A1z_ye.png
x_icon=A1x.png,A1x_ye.png
xx_icon=A1xx.png,A1xx_ye.png
c_icon=A1c.png,A1c_ye.png
v_icon=A1v.png,A1v_ye.png
b_icon=A1b.png,A1b_ye.png
n_icon=A1n.png,A1n_ye.png
nn_icon=A1nn.png,A1nn_ye.png
m_icon=A1m.png,A1m_ye.png

q_x_icon=A1q_x.png,A1q_x_ye.png,A1q_x.png,A1q_x_ye.png,A1q.png,A1q_ye.png
w_x_icon=A1w_x.png,A1w_x_ye.png,A1w_x.png,A1w_x_ye.png,A1w.png,A1w_ye.png
e_x_icon=A1e_x.png,A1e_x_ye.png,A1e_x.png,A1e_x_ye.png,A1e.png,A1e_ye.png
r_x_icon=A1r_x.png,A1r_x_ye.png,A1r_x.png,A1r_x_ye.png,A1r.png,A1r_ye.png
t_x_icon=A1t_x.png,A1t_x_ye.png,A1t_x.png,A1t_x_ye.png,A1t.png,A1t_ye.png
y_x_icon=A1y_x.png,A1y_x_ye.png,A1y_x.png,A1y_x_ye.png,A1y.png,A1y_ye.png
u_x_icon=A1u_x.png,A1u_x_ye.png,A1u_x.png,A1u_x_ye.png,A1u.png,A1u_ye.png
i_x_icon=A1i_x.png,A1i_x_ye.png,A1q_i.png,A1i_x_ye.png,A1i.png,A1i_ye.png
o_x_icon=A1o_x.png,A1o_x_ye.png,A1o_x.png,A1o_x_ye.png,A1o.png,A1o_ye.png
p_x_icon=A1p_x.png,A1p_x_ye.png,A1p_x.png,A1p_x_ye.png,A1p.png,A1p_ye.png

a_x_icon=A1a_x.png,A1a_x_ye.png,A1a_x.png,A1a_x_ye.png,A1a.png,A1a_ye.png
s_x_icon=A1s_x.png,A1s_x_ye.png,A1s_x.png,A1s_x_ye.png,A1s.png,A1s_ye.png
d_x_icon=A1d_x.png,A1d_x_ye.png,A1d_x.png,A1d_x_ye.png,A1d.png,A1d_ye.png
f_x_icon=A1f_x.png,A1f_x_ye.png,A1f_x.png,A1f_x_ye.png,A1f.png,A1f_ye.png
g_x_icon=A1g_x.png,A1g_x_ye.png,A1g_x.png,A1g_x_ye.png,A1g.png,A1g_ye.png
h_x_icon=A1h_x.png,A1h_x_ye.png,A1h_x.png,A1h_x_ye.png,A1h.png,A1h_ye.png
j_x_icon=A1j_x.png,A1j_x_ye.png,A1j_x.png,A1j_x_ye.png,A1j.png,A1j_ye.png
k_x_icon=A1k_x.png,A1k_x_ye.png,A1k_x.png,A1k_x_ye.png,A1k.png,A1k_ye.png
l_x_icon=A1l_x.png,A1l_x_ye.png,A1l_x.png,A1l_x_ye.png,A1l.png,A1l_ye.png

z_x_icon=A1z_x.png,A1z_x_ye.png,A1z_x.png,A1z_x_ye.png,A1z.png,A1z_ye.png
x_x_icon=A1x_x.png,A1x_x_ye.png,A1x_x.png,A1x_x_ye.png,A1x.png,A1x_ye.png
c_x_icon=A1c_x.png,A1c_x_ye.png,A1c_x.png,A1c_x_ye.png,A1c.png,A1c_ye.png
v_x_icon=A1v_x.png,A1v_x_ye.png,A1v_x.png,A1v_x_ye.png,A1v.png,A1v_ye.png
b_x_icon=A1b_x.png,A1b_x_ye.png,A1b_x.png,A1b_x_ye.png,A1b.png,A1b_ye.png
n_x_icon=A1n_x.png,A1n_x_ye.png,A1n_x.png,A1n_x_ye.png,A1n.png,A1n_ye.png
m_x_icon=A1m_x.png,A1m_x_ye.png,A1m_x.png,A1m_x_ye.png,A1m.png,A1m_ye.png
--
#角标icon
q_3sicon=A3q.png,A3q_ye.png
w_3sicon=A3w.png,A3w_ye.png
e_3sicon=A3e.png,A3e_ye.png
r_3sicon=A3r.png,A3r_ye.png
t_3sicon=A3t.png,A3t_ye.png
y_3sicon=A3y.png,A3y_ye.png
u_3sicon=A3u.png,A3u_ye.png
i_3sicon=A3i.png,A3i_ye.png
o_3sicon=A3o.png,A3o_ye.png
p_3sicon=A3p.png,A3p_ye.png
a_3sicon=A3a.png,A3a_ye.png
s_3sicon=A3s.png,A3s_ye.png
d_3sicon=A3d.png,A3d_ye.png
f_3sicon=A3f.png,A3f_ye.png
g_3sicon=A3g.png,A3g_ye.png
h_3sicon=A3h.png,A3h_ye.png
j_3sicon=A3j.png,A3j_ye.png
k_3sicon=A3k.png,A3k_ye.png
l_3sicon=A3l.png,A3l_ye.png
z_3sicon=A3z.png,A3z_ye.png
x_3sicon=A3x.png,A3x_ye.png
c_3sicon=A3c.png,A3c_ye.png
v_3sicon=A3v.png,A3v_ye.png
b_3sicon=A3b.png,A3b_ye.png
n_3sicon=A3n.png,A3n_ye.png
m_3sicon=A3m.png,A3m_ye.png

# 1=cn 2=letter 3=fun 4=edit 5=number 6=symcn 7=symen 8=emoji 9=symsp
#   -501 ϟ12键
# 按键文字色
[textcolor]
