#ifndef NATIVE_ERROR_H
#define NATIVE_ERROR_H

#include <cstdint>
#include <string>

enum NativeErrorCode : int32_t {
    IME_SUCCESS = 0,
    IME_INVALID_ARGUMENT = 1001,
    IME_INVALID_HANDLE = 1002,
    IME_UNSUPPORTED_OPERATION = 1003,
    IME_INVALID_UTF8 = 1004,
    IME_SERIALIZATION_ERROR = 1005,
    IME_BUFFER_ALLOCATION_FAILED = 1006,
    IME_ENGINE_NOT_INITIALIZED = 1007,
    IME_ENGINE_INTERNAL_ERROR = 1008,
    IME_NATIVE_BRIDGE_ERROR = 1009,
    IME_ABI_VERSION_MISMATCH = 1010,
    IME_INVALID_CONFIG = 1011,
    IME_INVALID_SCHEME = 1012,
    IME_LEXICON_NOT_FOUND = 1013,
    IME_LEXICON_LOAD_FAILED = 1014,
    IME_INVALID_PAGE = 1015,
    IME_INVALID_CANDIDATE = 1016,
    IME_UNKNOWN_ERROR = 1099,
};

std::string ErrorMessageForCode(int32_t code);

#endif
